### PR TITLE
fixed broken azure deployment

### PR DESCRIPTION
**Pull request by starmaerker**

### CODE REVIEW

**Comment by jarjan** [comment]
@starmaerker I guess we should run `npm install` after each deployment. Same issue that @hikes101 had on his local environment.

**Comment by pheeria** [comment]
@jarjan but

**Comment by starmaerker** [comment]
> I guess we should run npm install after each deployment.
@jarjan On the serverside it happens automatically or do you mean locally?

**Comment by pheeria** [comment]
[Website not working](https://trello.com/c/2fn09Veu/30-website-not-working)

**Pull request merged**
