### PR TITLE
Features/lazy load

### LINKED ISSUE #175: Lazy load images
- [ ] Run Chrome Dev Audit
- [ ] Check recommendations for event images

### PR DESCRIPTION
**Pull request by danielstreif**
**What**:
- use lazy loading to reduce unnecessary data usage

**How**:
- [using event handlers](https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/#using_event_handlers_the_most_compatible_way)

**Problems**:
- how to use `document.addEventListener("DOMContentLoaded", function() {...}` with Express

**Checklist**:

- [ ] Documentation added to the
      [README](https://github.com/Lernwerkstatt/site/blob/master/README.md)
- [ ] Tests
- [ ] Ready to be merged
      

Fixes #175

### CODE REVIEW

**Comment by danielstreif** [comment]
> I think we can use more modern approach by Addi Osmani, by using `loading="lazy"` and polyfilling it to other browser not supporting it. More here: https://addyosmani.com/blog/lazy-loading/

Thanks for the link. What do you think about this hybrid lazy loading with `vanilla-lazyload` then? Would that work for us? It still would need polyfilling for IE but most other browsers should be covered.

**Comment by jarjan** [comment]
@danielstreif yes, sure.
We can use something like this:
```
<img data-src="unicorn.jpg" loading="lazy" alt=".." class="lazyload"/>
<img data-src="cats.jpg" loading="lazy" alt=".." class="lazyload"/>
<img data-src="dogs.jpg" loading="lazy" alt=".." class="lazyload"/>

<script>
  if ('loading' in HTMLImageElement.prototype) {
      const images = document.querySelectorAll("img.lazyload");
      images.forEach(img => {
          img.src = img.dataset.src;
      });
  } else {
    let script = document.createElement("script");
    script.async = true;
    script.src =
      "https://cdnjs.cloudflare.com/ajax/libs/lazysizes/4.1.8/lazysizes.min.js";
    document.body.appendChild(script);
  }
</script>
```

**Comment by pheeria** [comment]
I really like the conversation in this issue! 🎉

**Comment by danielstreif** [comment]
> @danielstreif yes, sure.
> We can use something like this:
> 
> ```
> 
> 
> 
> 
> <script>
>   if ('loading' in HTMLImageElement.prototype) {
>       const images = document.querySelectorAll("img.lazyload");
>       images.forEach(img => {
>           img.src = img.dataset.src;
>       });
>   } else {
>     let script = document.createElement("script");
>     script.async = true;
>     script.src =
>       "https://cdnjs.cloudflare.com/ajax/libs/lazysizes/4.1.8/lazysizes.min.js";
>     document.body.appendChild(script);
>   }
> </script>
> ```

I implemented your suggestion and it works for Firefox. I used the network inspection for images to check on it and the images were just loaded when the modal was opened. However, the actual native lazy loading in Chrome doesn't seem to work, all images are loaded in the beginning. Could it be because it's a modal?

**Comment by jarjan** [comment]
@danielstreif probably, I'm not sure how exactly native lazy loading works, maybe modal is in viewport somehow, thus image loads instantly.

**Comment by pheeria** [comment]
@danielstreif while you're doing @jarjan 's suggestion, could you please avoid using jQuery and prefer `document.querySelector` instead? We'd like to ditch jQuery with Bootstrap 5.

**Comment by danielstreif** [comment]
@jarjan @pheeria I pushed a new version with intersection observer and event listener according to [these instructions](https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/) but it seems a bit bulky. What do you think? The intersection observer works fine for chrome and firefox but I couldn't test it in other browsers. In general, is there a way to test how it looks in different browsers without installing a ton of different ones?

**Comment by danielstreif** [comment]
> Sorry for taking long. I didn't have time to read about the subject.
> This looks very promising, thanks for implementing.
> As for testing it, would you like to try https://www.browserstack.com/ ?
> I never used it, but it seems to be a nice way to go. Maybe @jarjan knows more?
> I've tested it on my local machine, it worked with Safari as well.
> According to https://caniuse.com/#search=intersection only IE can be a problem.
> And I looked at our Analytics, it shouldn't be

Thanks, I'll look into browserstack! And good to know about the IE user rate :smile:

**Comment by pheeria** [comment]
@jarjan could you also take a look at this?
@danielstreif could you resolve the package.json conflicts?

**Pull request merged**
