### PR TITLE
Updated design (#168, #198)

### PR DESCRIPTION
**Pull request by jarjan**
**What**:

Updated design.

**Why**:

More accessible colors.

**How**:

**Checklist**:

- [x] Documentation added to the
      [README](https://github.com/Lernwerkstatt/site/blob/master/README.md)
- [x] Tests
- [x] Ready to be merged
      

Fixes  #168 and #198 

Screenshot_2019-10-31 Die Lernwerkstatt

### CODE REVIEW

**Comment by pheeria** [comment]
I think the contrast is still not good enough.

**Comment by pheeria** [comment]
Some color science from [here] :)
image

image

image

**Comment by pheeria** [comment]
I think, there are a lot of colors.
Could we make it like before, but every use the dark green?
By the way, Bianca didn't like the blue links.

**Comment by jarjan** [comment]
Please re-review @pheeria  :)

**Comment by jarjan** [comment]
@pheeria @danielstreif can we merge it? WDYT?

**Comment by danielstreif** [comment]
> @pheeria @danielstreif can we merge it? WDYT?

Looks good to me :+1:

**Pull request merged**
